title: Zhenqin Li
description: Personal academic homepage of Zhenqin Li
url: "https://zqinli.github.io"
baseurl: ""
markdown: kramdown

collections:
  publications:
    output: true
    permalink: /publications/:name/

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: publications
    values:
      layout: page

exclude:
  - vendor
  - node_modules
  - .sass-cache
  - .jekyll-cache
  - .bundle
  - Gemfile.lock
  - README.md
